server:
  port: ":8080"

database:
  master:
    ssl_mode: "disable"

  slaves: []

  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 30m

rabbitmq:
  host: "rabbitmq"
  port: 5672
  user: "guest"
  password: "guest"
  retries: 3
  pause: 1s
  not_exchange: "notify-exchange"
  retry_not_exchange: "notify-exchange-retry"
  not_queue: "notify-queue"
  not_queue_retry: "notify-retry"
  routing_key: "notify"
  ttl: 60000

retry:
  attempts: 3
  delay: 50ms
  backoff: 2.0

workers:
  count: 5
