server:
  port: ":8080"

database:
  master:
    host: "db"
    port: "5432"
    user: "postgres"
    pass: ""
    name: "notifier"
    ssl_mode: "disable"

  slaves: []

  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 30m

rabbitmq:
  host: "rabbitmq"
  port: 5672
  user: "guest"
  password: "guest"
  retries: 3
  pause: 1s
  exchange: "notify-exchange"
  queue: "notify-queue"
  retry_queue: "notify-retry"
  dlq: "notify-dlq"
  routing_key: "notify"

retry:
  attempts: 3
  delay: 50ms
  backoff: 2.0

workers:
  count: 5

redis:
  address: "redis:6379"
  password: ""
  database: "0"

email:
  smtp_host: "smtp.mailtrap.io"
  smtp_port: "587"
  username: "smtp_user"
  password: "smtp_pass"
  from: "example@example.com"

telegram:
  token: ""
  chat_id: ""